---
- name: Ensure Caddy configuration directory exists
  ansible.builtin.file:
    path: "{{ homelab_data_dir }}/caddy"
    state: directory
    mode: '0755'

- name: Deploy Caddyfile
  ansible.builtin.template:
    src: Caddyfile.j2
    dest: "{{ caddy_file_path }}"
    mode: '0644'
  notify: Reload caddy service

- name: Ensure active Caddy instance reloads configuration
  ansible.builtin.systemd:
    name: caddy.service
    state: reloaded
    scope: user
  failed_when: false

