---
- name: Install avahi-tools package
  ansible.builtin.dnf:
    name: avahi-tools
    state: present
  become: true

- name: Deploy avahi-alias template systemd unit
  ansible.builtin.template:
    src: avahi-alias@.service.j2
    dest: /etc/systemd/system/avahi-alias@.service
    mode: '0644'
  become: true
  notify: Reload system systemd

- name: Flush handlers to reload systemd daemon if unit changed
  ansible.builtin.meta: flush_handlers

- name: Enable and start avahi alias services
  ansible.builtin.systemd:
    name: "avahi-alias@{{ item }}.service"
    enabled: true
    state: started
  loop: "{{ avahi_aliases }}"
  become: true
