---
- name: Reload user systemd
  ansible.builtin.systemd:
    daemon_reload: true
    scope: user

- name: Restart sillytavern service
  ansible.builtin.systemd:
    name: sillytavern.service
    state: restarted
    scope: user

- name: Restart llama-swap service
  ansible.builtin.systemd:
    name: llama-swap.service
    state: restarted
    scope: user

- name: Restart hermes-agent service
  ansible.builtin.systemd:
    name: hermes-agent.service
    state: restarted
    scope: user

- name: Restart homepage service
  ansible.builtin.systemd:
    name: homepage.service
    state: restarted
    scope: user

- name: Restart glances service
  ansible.builtin.systemd:
    name: glances.service
    state: restarted
    scope: user

- name: Restart searxng service
  ansible.builtin.systemd:
    name: searxng.service
    state: restarted
    scope: user

- name: Restart open-webui service
  ansible.builtin.systemd:
    name: open-webui.service
    state: restarted
    scope: user
