---
- name: Reload system systemd
  ansible.builtin.systemd:
    daemon_reload: true
  become: true

- name: Restart avahi alias services
  ansible.builtin.systemd:
    name: "avahi-alias@{{ item }}.service"
    state: restarted
  loop: "{{ avahi_aliases }}"
  become: true
