---
st_data_dir: "{{ homelab_data_dir }}/sillytavern"
piclaw_home_dir: "{{ homelab_data_dir }}/piclaw/home"
piclaw_workspace_dir: "{{ homelab_data_dir }}/piclaw/workspace"
piclaw_port: 8080

avahi_aliases:
  - sillytavern.local
  - forgejo.local
  - llama-swap.local
  - openwebui.local
  - hermes.local
  - swarmui.local
  - wan2gp.local
